### ISSUE TITLE
builder running on an old centos (version 7)

### ISSUE THREAD

**Issue by hannesm** [ocurrent/ocaml-ci#112]
Hi,

I noticed that the centos builder uses centos7, while centos8 has been out for several months (according to wikipedia September 2019). Is there a good reason for that, or could the centos builder be upgraded to centos 8?

Thanks.

**Comment by hannesm** [comment]
Additionally, I tried to mark a package not available on centos 7 (unfortunately opam only let's me express this via `available: os-distribution != "centos"` which marks it as unavailable for centos, independent of version), and the CI reported an error in the builder (where I expected a pass / warning -- similar to if a package has lower/upper bounds on the OCaml version). The CI output:
```
#19 [stage-0 12/12] RUN --mount=type=cache,target=/home/opam/.opam/download-...
#19 1.104 mirage-crypto is now pinned to git+file:///src#master (version ~dev)
#19 1.106 mirage-crypto-rng is now pinned to git+file:///src#master (version ~dev)
#19 1.108 mirage-crypto-pk is now pinned to git+file:///src#master (version ~dev)
#19 1.599 [ERROR] mirage-crypto-rng = ~dev unmet availability conditions: os-distribution != "centos"
#19 1.600 'opam install -tv .' failed.
#19 ERROR: executor failed running [/bin/sh -c opam install -tv .]: runc did not terminate sucessfully
```

(from https://ci.ocamllabs.io/github/mirage/mirage-crypto/commit/1fa0105e70c74c0422584d5b9fbd704bac9fedfd/variant/centos)

**Comment by talex5** [comment]
I've added a pattern to match this - it now reports as `[SKIP]`.

https://ci.ocamllabs.io/github/mirage/mirage-crypto/commit/1fa0105e70c74c0422584d5b9fbd704bac9fedfd/variant/centos

**Comment by hannesm** [comment]
@talex5 thanks, though I'd actually be more interested in having a more current centos builder :)

**Comment by talex5** [comment]
I've updated the base image builder to the latest ocaml-dockerfile so it will build centos-8 images: 
https://github.com/ocurrent/docker-base-images/pull/26

**Comment by talex5** [comment]
Should be building with centos-8 now!

**Comment by hannesm** [comment]
thanks @talex5, works fine for me
