### ISSUE TITLE
Ubuntu 20.04 jobs blocked on keyboard-configuration dialog

### ISSUE THREAD

**Issue by CraigFe** [ocurrent/ocaml-ci#226]
Currently, certain CI jobs on the Ubuntu 20.04 runner are getting blocked indefinitely on a `keyboard-configuration` dialog triggered by `debconf`:

```
#15 229.6   95. Ukrainian
#15 229.6   96. Urdu (Pakistan)
#15 229.6   97. Uzbek
#15 229.6   98. Vietnamese
#15 229.6   99. Wolof
#15 229.6 Country of origin for the keyboard: 2020-07-21 08:59.46: Cancelling: Timeout (60.0 minutes)
Job cancelled
```

See for instance: https://ci.ocamllabs.io/github/mirage/irmin/commit/66366d36b7b822ffe73b4ebff27892d7626b4949/variant/ubuntu-20.04-ocaml-4.10.

This appears to happen as part of the `opam depext` call, where passing `-yy` to `apt-get install` is not sufficient to make the install run non-interactively. See https://github.com/moby/moby/issues/27988#issuecomment-462809153, which suggests using `debconf-set-selections` to explicitly tell `debconf` to be non-interactive.

**Comment by avsm** [comment]
This should be fixed now in the live infra; could you confirm @CraigFe ?

**Comment by CraigFe** [comment]
Here's a trace from ~10 mins ago that's still blocked in the same way: https://ci.ocamllabs.io/github/mirage/irmin/commit/05168f5e5e0ef5ffaac4b191af35e6a094a9fdee/variant/ubuntu-20.04-ocaml-4.10.

Looks like it may not be fixed.

**Comment by talex5** [comment]
You'll need to re-pull the image (at https://ci.ocamllabs.io:8100/) too.

**Comment by avsm** [comment]
Re-pulled; its rebuilding jobs now

**Comment by avsm** [comment]
Looks like its working now

```
 #15 19.48 The following command needs to be run through "sudo":
#15 19.48     apt-get install -qq -yy debianutils gnuplot-x11 libgmp-dev m4 perl pkg-config
#15 19.49 sudo: setrlimit(RLIMIT_CORE): Operation not permitted
#15 34.17 debconf: delaying package configuration, since apt-utils is not installed
#15 34.83 Selecting previously unselected package keyboard-configuration.
#15 34.83 (Reading database ... 
(Reading database ... 5%
```

https://ci.ocamllabs.io:8100/job/2020-07-23/113406-ci-ocluster-build-f0bc7c

**Comment by CraigFe** [comment]
Indeed; thanks all!
