### ISSUE TITLE
make ppc64le/ppc64be opt-in

### ISSUE THREAD

**Issue by avsm** [ocurrent/ocaml-ci#237]
In the analysis phase, we could scan for C files in the opam package and/or a `x-test-on-arch: ppc64` flag and turn off that architecture if not found.

The reason is that it would be nice to activate ppc64be testing, but we only have about 8 CPUs available on that arch. So that means we do need to minimise the number of packages using it.

**Comment by novemberkilo** [comment]
Closing this as we have ppc-hardware now.
