### ISSUE TITLE
OCaml-CI doesn't support the `extra-source` field

### ISSUE THREAD

**Issue by TheLortex** [ocurrent/ocaml-ci#277]
We're using OCaml-CI for [ocaml-gmp](https://github.com/mirage/ocaml-gmp) but it seems to fail because is uses `wget` as a fallback option to fetch GMP sources. The GMP sources were expected to be fetched using the `extra-source` field of the opam definition, but it doesn't look like it's the case. 

* CI log: https://ci.ocamllabs.io/github/mirage/ocaml-gmp/commit/801dda44df59702989d28d8abf57b6d7f366bf7e
* Opam file: https://github.com/mirage/ocaml-gmp/blob/master/gmp.opam

**Comment by talex5** [comment]
As a work-around, you could use `git submodule add` to add the correct version of gmp. The CI will download and cache that for you.

**Comment by avsm** [comment]
I think a submodule is generally better here rather than extra-sources, in the case of gmp. The fallback rule to `wget` isnt great inside the dune file.

**Comment by TheLortex** [comment]
As gmp use mercurial for versioning I don't think it's possible to add it as a submodule. 
A solution is to simply add the archive in the source tree, so I'll probably do that and remove the `wgeŧ` usage at all.

**Comment by TheLortex** [comment]
Closing as I used a workaround.

**Comment by avsm** [comment]
Isn't this still a problem in ocaml-ci that needs to be fixed?

**Comment by TheLortex** [comment]
Probably, but it doesn't look like there is any user of that feature for now !
