### ISSUE TITLE
monorepo: does not support compiler versions not in base images

### ISSUE THREAD

**Issue by emillon** [ocurrent/ocaml-ci#281]
Hi,

We're having the following situation in RWO:
- the version for ocaml and ocaml-base-compiler is set to 4.10.2 in the lock file
- in the analysis phase, it considers only 4.10 platforms and queries for (ocaml=4.10.2, opam-monorepo=0.1.0, dune=2.7.1)
- this fails because the platform has 4.10.1 installed:

```
[INFO] Can't find all required versions.
Selected: base-bigarray.base base-threads.base base-unix.base ocaml-config.2
          ocaml-base-compiler&opam-monorepo-deps ocaml-base-compiler
          ocaml-variants
- ocaml -> ocaml.4.10.1
    ocaml-base-compiler 4.10.1 requires = 4.10.1
- ocaml-base-compiler -> ocaml-base-compiler.4.10.1
    User requested = 4.10.1
- ocaml-variants -> (problem)
    Rejected candidates:
      ocaml-variants.4.13.0+trunk+no-flat-float-array: In same conflict class (ocaml-core-compiler) as ocaml-base-compiler
      ocaml-variants.4.13.0+trunk+nnp: In same conflict class (ocaml-core-compiler) as ocaml-base-compiler
      ocaml-variants.4.13.0+trunk+fp+flambda: In same conflict class (ocaml-core-compiler) as ocaml-base-compiler
      ocaml-variants.4.13.0+trunk+fp: In same conflict class (ocaml-core-compiler) as ocaml-base-compiler
      ocaml-variants.4.13.0+trunk+flambda: In same conflict class (ocaml-core-compiler) as ocaml-base-compiler
      ...
- opam-monorepo-deps -> (problem)
    Rejected candidates:
      opam-monorepo-deps.dev: Requires ocaml = 4.10.2
```

I'm not sure what to do in that case; it would be fine to create a new switch where dune and opam-monorepo would be installed.

A similar problem would appear if the project locks a compiler variant (e.g. the application needs flambda).

**Comment by avsm** [comment]
The lock file should be flexible regarding the minor OCaml version. I dont think its a good idea to lock it to the minor version in monorepo. (e.g. `ocaml >= "4.10.0" & < "4.11.0~"`)

Doesnt entirely fix the problem here (e.g. with variants), but would unblock RWO.

**Comment by emillon** [comment]
For RWO we have a workaround: I added a conflict in the opam file so that it selects 4.10.1. It's also possible to edit the lock file by hand. (this is fragile since it will break the build once the base image is updated of course)

I don't think we should add a special case the compiler for this. The point of using a lock file is to know exactly which dependencies are used. If the compiler constraint stays flexible, the same lock file can produce different results depending on the moon phase^w^wbase images.

**Comment by talex5** [comment]
You're already ignoring the micro component when selecting the platform:

https://github.com/ocurrent/ocaml-ci/blob/7266dc74c1263362342b8745b3bfbbe043ba0c48/lib/opam_monorepo.ml#L103

If so, you should also relax the constraint when passing it to the solver. Or maybe not even constrain the compiler at all, since you already picked a platform with the compiler you want.

**Comment by emillon** [comment]
Yes, I mentioned that in the PR: https://github.com/ocurrent/ocaml-ci/pull/279#issuecomment-742495452 - I thought it would be a problem but only later :smile:
