### ISSUE TITLE
monorepo: fails when dependencies are locked using a newer version of opam-repository

### ISSUE THREAD

**Issue by emillon** [ocurrent/ocaml-ci#282]
Hi,

At the moment the following happens for monorepo builds:
- during the analysis phase, the solver is queried for ocaml, dune and opam-monorepo. The oldest opam-repository commit that knows about that solution is selected.
- during the build phase, the lock file is pinned in order to resolve depexts.

The issue is that if the lock file has been produced with an opam-repository state that's more recent than the result of the analysis, it won't be able to compute the depexts.

As an example (inspired by a true story with RWO), querying for ocaml=4.10.1, dune=2.7.1, opam-monorepo=0.1.0 resolves to ocaml/opam-repository@aaf8fed5fa134979c4552e283800798ac3f64366. If the project refers to conf-gmp, today it will get locked to version 3. But this version has been uploaded only after that opam-repository commit.

As a workaround, conflicting with conf-gmp > 2 kind of works, but this is only a short term solution since it will apply to all transitive dependencies released after.

The root issue is that we need access to the repository to determine depexts. That's a known opam-monorepo 0.1.0 limitation which is going to be lifted soon, but I'm wondering if there's something we can do in the meantime on the CI side. Maybe passing the pin-depends to the solver would work, but if done too naively it will try to install them via opam in the build phase.

**Comment by avsm** [comment]
Can't this be fixed just by rerunning the analysis? That'll grab the latest opam-repo.

**Comment by emillon** [comment]
At the moment the "actual" project dependencies are not passed to the solver - it's only used to determine how it can install dune and opam-monorepo. So the opam-repository version is the best one for these (oldest correct one) and rerunning the analysis doesn't change the result.

**Comment by emillon** [comment]
I'll try to pass the transitive revdeps as `pinned_pkgs`, that should ensure the selected repository contains these

**Comment by talex5** [comment]
If monorepo is getting the revdeps from the opam files in the commit being tested, then it shouldn't matter what version of opam-repository is used.

If you want to install using the versions in opam-repository instead then you should probably pass the whole lock-file to the solver. Though that seems a bit odd.
