### ISSUE TITLE
No matching version of ocamlformat, last ocamlformat release makes lint-fmt fail

### ISSUE THREAD

**Issue by gpetiot** [ocurrent/ocaml-ci#312]
Hi,
It seems the opam cache is not updated, as it does not find the last release of ocamlformat 0.17.0 (see https://ci.ocamllabs.io/github/realworldocaml/mdx/commit/3841447381115fdb4bf60b6f3f8f5fef5fa53326/variant/(lint-fmt)), I was wondering if the update was automatic but could take some time, or if I something needs to be in the project source to indicate ocaml-ci to update the opam packages. Thanks for your great work on ocaml-ci!

**Comment by avsm** [comment]
This should all be in sync now. Can you confirm that ocamlformat's working ok?

**Comment by gpetiot** [comment]
Hi, I still get the same issue, the version has not been found.

**Comment by emillon** [comment]
This is happening on opam-compiler too: https://ci.ocamllabs.io/github/ocaml-opam/opam-compiler/commit/5fa28d623f06d8be6856ac167a11fbf347caef19/variant/(lint-fmt)

**Comment by gpetiot** [comment]
It looks like it's fixed now, thanks!
