### ISSUE TITLE
ocaml-ci assumes default branch is "master"

### ISSUE THREAD

**Issue by emillon** [ocurrent/ocaml-ci#318]
Hi,

When the default branch is not named "master", it does not display the status correctly.

For example mirage/ca-certs uses "main", and it shows a gray icon for that repository on https://ci.ocamllabs.io/github/mirage.

**Comment by maiste** [comment]
This has been addressed by https://github.com/ocurrent/ocaml-ci/pull/617. Feel free to reopen.
