### ISSUE TITLE
Ocamlformat upgrades

### ISSUE THREAD

**Issue by NathanReb** [ocurrent/ocaml-ci#330]
Thanks to ocaml-ci we can now reliably format our ocaml projects using ocamlformat as it makes sure your project is correctly formatted at any given time and that's a truly wonderful achievement!

From my recent adventures with ocaml-ci and ocamlformat, it appears that a manual step from ocaml-ci maintainers is required for the CI `lint-fmt` job to have access to newly released ocamlformat's versions.

It'd be even more wonderful of a feature if this was automated so that the delay between the release of a new ocamlformat and the moment one can actually use it in its project while having ocaml-ci checking formatting is reduced.

**Comment by emillon** [comment]
Related to #261

**Comment by maiste** [comment]
As the various `ocamlformat` PRs fixed it, I'm closing this. Feel free to reopen.
