### ISSUE TITLE
monorepo: do not assert fail with flexible compiler versions

### ISSUE THREAD

**Issue by avsm** [ocurrent/ocaml-ci#339]
Right now if the `ocaml` dependency is not strictly `=<version>`, we get an assert failure in the build:

https://ci.ocamllabs.io/github/ocamllabs/opam-monorepo/commit/51adf6c57ac869210e517818a902fc864da85f3d/variant/(analysis)

```
2021-05-05 12:43.24: Job failed: "Assert_failure lib/opam_monorepo.ml:60:9"
```

Need to be able to specify >= and < patch versions so lifting this constraint would be useful in the CI.

**Comment by avsm** [comment]
see #302

**Comment by maiste** [comment]
This issue was closed on `opam-monorepo`. Is this mechanism available in the project or should we consider closing this issue and leaving `opam-monorepo` with fixed `ocaml` versions?
(cc @emillon)

**Comment by maiste** [comment]
I see! Thanks for your answer 😄

**Comment by maiste** [comment]
Closing as it does not seem to be required by `opam-monorepo` for now. Feel free to reopen.
