### ISSUE TITLE
CI is broken with non-trivial dependencies

### ISSUE THREAD

**Issue by hannesm** [ocurrent/ocaml-ci#381]
Hello,

thank you very much for the ocaml-ci. We just encountered an interesting corner case where it does not work: https://ci.ocamllabs.io/github/roburio/happy-eyeballs/commit/4a91542ac035eca1590932c9acb2434875a058f9/variant/alpine-3.13-4.13

The repository happy-eyeballs consists of 3 opam packages: happy-eyeballs, happy-eyeballs-lwt, happy-eyeballs-mirage. The happy-eyeballs package provides a pure implementation of the algorithm/RFC, which is used by dns-client (to first attempt DNS-over-TLS, then DNS-over-TCP - with all nameservers from /etc/resolv.conf). The happy-eyeballs-lwt and happy-eyeballs-mirage depend on dns-client for DNS resolution.

Now the CI fails with the error `Error: Library "happy-eyeballs" not found.` (while compiling dns-client), though opam reports that `installed happy-eyeballs.dev` in its output. A manual installation works fine as well (first happy-eyeballs, then dns-client, then happy-eyeballs-lwt/happy-eyeballs-mirage).

Thanks for reading, and maybe there's something deeper to look into how package installations are scheduled?

Best,

Hannes

**Comment by hannesm** [comment]
I ran into this issue again at https://github.com/mirage/metrics/pull/53 -- are there any plans to implement a fix, like the one suggested by @dra27?

**Comment by hannesm** [comment]
Hi again, I'm still curious about this issue - and was wondering whether fixing this issue is on the roadmap? It looks like @dra27 has a good plan about how to fix this.

**Comment by maiste** [comment]
Thanks for the quick reply! I agree with you. 
1. Indeed, this one seems to be a reasonable trade. As it depends on the _repo_ construction, it should be the responsibility of the developers to handle this case and not the CI.
2. Agree with that too! In this case, it is not only related to `happyeyeballs` but also to other packages. It's linked with this [dune issue](https://github.com/ocaml/dune/issues/5621) open by @talex5 which makes it hard to build examples without having the same issue in the CI. In the case of `happyeyeballs`, I image `dune build @all` work if you pin the right dependencies or vendors `dns-client` (as you suggested).

**Comment by dra27** [comment]
Another corner case has cropped up for this as well - the `(lint-doc)` job fails if it's testing one of odoc's dependencies (e.g. now that odoc depends on camlp-streams, that job is [routinely failing](https://ci.ocamllabs.io/github/ocaml/camlp-streams/commit/fa2ca92ed08d1c05c65bc78c31b98c3fee12afe4/variant/(lint-doc))).

**Comment by hannesm** [comment]
Closing, I found another CI system where it just worked. Also, quoting from the PR "So perhaps we should regard the CI rejecting this as a feature?"
