### ISSUE TITLE
lint-fmt build fails because it uses too recent a compiler

### ISSUE THREAD

**Issue by NathanReb** [ocurrent/ocaml-ci#383]
This issue might be considered a duplicate of #261 but I opened a separate issue as that one has been closed and I'm not sure how related they actually are.

I recently ran into this kind of error:
https://ci.ocamllabs.io/github/NathanReb/ppx_yojson/commit/dc90d842097cccacfa8b751abeee7356e92b3f99/variant/(lint-fmt)

If I understand correctly, the lint-fmt build fails because it's running on a 4.13 opam switch and my project uses an ocamlformat version that's incompatible with 4.13.

I'll happily upgrade ocamlformat in that case but this seems like unwanted behaviour from ocaml-ci nonetheless. I imagine it to be legitimate to stick to an old ocamlformat version for as long as the formatting is unstable between versions so, while it isn't for me, it might be a problem for some other users. It is also worth considering that it will potentially happen everytime a new compiler is released, although I think ocamlformat should become compatible with future compiler versions in the future as it will 
have its own parser (@gpetiot and @emillon should be able to confirm whether this is true).

Not sure what the fix should be but I guess having an empty switch or at least one without invariant would be nice so that one is free to use whatever ocamlformat version they want.

**Comment by emillon** [comment]
>  I think ocamlformat should become compatible with future compiler versions in the future as it will
have its own parser

Just replying to this part: yes, I think that's correct. Nowadays I don't think that ocamlformat has any compat layers left so it should be buildable with the latest version of the compiler (of course, the features it's able to format are tied to the version you use)

**Comment by emillon** [comment]
(This is the case from 0.19.0 onwards. There's a `< 4.14` constraint in the opam file but I'm not sure it's relevant)

**Comment by maiste** [comment]
Closing at it was fixed by #472. Feel free to reopen if needed.
