### ISSUE TITLE
Option for disabling format from dune-project

### ISSUE THREAD

**Issue by tmcgilchrist** [ocurrent/ocaml-ci#406]
CI could search for `(formatting (enabled_for dune))` in the dune-project file and enable / disable formatting based off that. 

Adding an .ocamlformat file containing "disable" could also work.

**Comment by kit-ty-kate** [comment]
side note: `(formatting disabled)` in the dune-project file is also valid.

**Comment by tmcgilchrist** [comment]
The dune documentation on [formatting](https://dune.readthedocs.io/en/stable/dune-files.html#formatting) and the [How to Set up Automatic Formatting](https://dune.readthedocs.io/en/stable/howto/formatting.html) shows how to setup formatting in ocaml-ci. 

In short:
 * put `(formatting disabled)` in your dune-project file to disable formatting completely 
 * Using `(dune lang 2.0)` formatting is turned on by default
 * Selectively enable formatting via `(formatting (enabled_for <languages>))` 
 
See the linked docs for more details.
