### ISSUE TITLE
Make ocaml-ci solver an ocluster service.

### ISSUE THREAD

**Issue by tmcgilchrist** [ocurrent/ocaml-ci#446]
- Move the ocaml-ci solver to be a general cluster service, so on an opam-repository merge, the entire cluster can work on solver jobs instead of just Toxis
- Potential in generalising the solver service to make it easier for other pipelines to adopt it (i.e. to make it common-place that systems track all merges to opam-repository and re-solve what they're trying to do with a minimum stable commit of opam-repository)
- Investigate ways of splitting and canonicalising dependencies to improve sharing of cached results, especially - or at least initially - in opam-health-check

Links:
- Support custom jobs https://github.com/ocurrent/ocluster/pull/156
- An OCurrent service for solving opam dependencies https://github.com/patricoferris/solver-service

**Comment by patricoferris** [comment]
Thanks for opening this issue @tmcgilchrist. Here is a little more information about the various branches that people may find useful.

https://github.com/patricoferris/solver-service contains:
 - The solver Cap'n P interface that is currently in OCaml-CI. This commit https://github.com/patricoferris/ocaml-ci/commit/1383540dba7e054842ba39eca9ec391e768f33ee swaps out the interfaces.
 - The solver service repository also shows in the `examples` how to use the new, unreleased `Custom` job API in OCluster to submit solver requests to a worker. See here: https://github.com/patricoferris/solver-service/blob/0a7b7646f7724e366731c101aa8908d81d609cb4/examples/submit.ml#L61

> Potential in generalising the solver service to make it easier for other pipelines to adopt it

Definitely, the service is already quite general and I think could be reused.

> Investigate ways of splitting and canonicalising dependencies to improve sharing of cached results, especially - or at least initially - in opam-health-check

Yes this would be great. Just to shed some more light on this, the idea is that many packages share dependencies. Most commonly these are the core libraries in the OCaml ecosystem such as `dune` or Stdlib replacements and currently in ocaml-ci dependencies are installed in one big step with:

```dockerfile
ENV DEPS="alcotest.1.5.0 alcotest-lwt.1.5.0 astring.0.8.5 base.v0.15.0 base-bigarray.base ..."
RUN opam depext --update -y obuilder.dev obuilder-spec.dev $DEPS
```

This means if two packages had exactly the same set of dependencies and versions except for one then there would be no sharing at all. Instead, the solver-service could offer a series of `DEPS_N` to install sequentially based on the order in which they must be installed (e.g. first `dune.x.y.z`, then all of the other packages). Then perhaps packages that share `dune.x.y.z` would share the cached build step.

**Comment by moyodiallo** [comment]
Will the [service-solver](https://github.com/patricoferris/solver-service) be integrated in `OCaml-CI` at some point ?

**Comment by tmcgilchrist** [comment]
Yes we want to move `ocaml-ci` to the use the solver service.

**Comment by MisterDA** [comment]
Also this will help running ocaml-ci-local on Windows :100:

**Comment by maiste** [comment]
Now that #634 is merged, should we consider closing this?

**Comment by tmcgilchrist** [comment]
Implemented in https://github.com/ocurrent/ocaml-ci/pull/634
