### ISSUE TITLE
 New routes to introduce commits and history in the context of refs (and PRs and MRs)

### ISSUE THREAD

**Issue by maiste** [ocurrent/ocaml-ci#529]
In the current version of the ocaml-ci, to access a specific ref, we are relying on the commit to display the build.  The route looks like this:
```
/:orga/:repo/commit/:commit_hash
```
It brings two issues:
* First, the design doesn't reflect what happens behind it and the objects we are manipulating.
* Second, it is impossible for the new design to distinguish between a branch or a PR with the same HEAD commit.

The solution is to separate the pull/merge requests from the branch refs. The new URLs would look like this:
```
/:orga/:repo/commit/:hash/ref/pull/:number
/:orga/:repo/commit/:hash/ref/mr/:number 
/:orga/:repo/commit/:hash/ref/tree/:name
```

It also allows us to bring more functionalities in the future (as an extension with `/history). Also, it is a better API to describe what we are trying to do. However, it has one drawback. We need to handle by hand the `:name` as there might be some `subject/area/content` branches. That's why we must introduce the `-` in the loop. This way, we can easily match the pattern in the URL.

**Comment by novemberkilo** [comment]
Note I am suggesting in #530 that we have a leading hyphen to separate the ref data. This may not be necessary but for now, it allows us to continue to support routes like 

```
/:orga/:repo/commit/:hash/[cancel,rebuild]
```

while still allowing us to use wildcard matching.

**Comment by maiste** [comment]
I agree :+1: It's import to keep legacy routes.

**Comment by novemberkilo** [comment]
I'm closing this as done seeing that we've had these routes in production since September, without incident.
