### ISSUE TITLE
Implement a Data model for the view and the metadata

### ISSUE THREAD

**Issue by maiste** [ocurrent/ocaml-ci#532]
The plan is to introduce a new database in `ocaml-ci` to store the information needed for the view to act without having to query the cache. The challenges are to ensure the data is up to date and everything is consistent between the cache and this view database. It would also solve some query problems that requires joining the `cache` with `ci_build_index` database.

**Comment by maiste** [comment]
I open this discussion about the schema we must introduce to simplify the request in the front end and not depends on the `cache` anymore. Last time we spent time on it, this was the schema that was chosen:
```
+-----------+----------+----------+---------+--------+--------+----------+
|           |          |          |         |        |        |          |
|    build  |  number  |  variant | started | queued | status |refs      |  ----->   key: (build, number)
|           |          |          |         |        |        |          |
+-----------+----------+----------+---------+--------+--------+----------+

+-------------+------------+-------------+
|organisation | description| repo list   | -------->  key: (organisation)
+-------------+------------+-------------+

+------+-------------+----------+
| repo | description | status   | --------->  key: (orga_id, repo)
+------+----+--------+----------+
| Orga id   |
+-----------+

```

I think we can iterate over this to reach a consensus about the tables we should add and how to fill them.

**Comment by benmandrew** [comment]
There is no table specifically for refs? Is this due to the complicated overlapping nature of PRs and branches?

Also, it is necessary to have `hash` and `last_updated` fields in the repo table: `last_updated` is aggregated from the refs similar to status and `hash` is from the default branch

**Comment by novemberkilo** [comment]
Is `build` meant to say `hash` for the first table? And to be clear, the first table is storing steps (or jobs), right? 

Also, echoing Ben's remarks, after looking more closely at Ben's work on the refs page I see that we're running into this issue of needing to calculate the total-run-time of a build by first getting all the steps associated to the build, and then using a utility like `Run_time.total_of_run_times jobs` -- should we be persisting this when we first calculate it? Similarly for the `build_created_at` timestamp of a build. I think we could store these in a `builds` table 

```
build_id | hash | build_number | refs | created_at | total_run_time | status | 
```

where `build_id` is an incrementing counter, and there can be only one entry per `(hash, build_number).` 

There would be a foreign key correspondence between `number` of the `step` table, and `build_number` of the `builds` table.

**Comment by novemberkilo** [comment]
I'm closing this as done -- it was part of the work on implementing build-history.
