### ISSUE TITLE
Spike - How to populate the new tables

### ISSUE THREAD

**Issue by maiste** [ocurrent/ocaml-ci#533]
As described in #531 and #532, we will introduce a new database for the view. This issue is opened to discuss the last step about how we want to populate the database. Basically, we have three options:
* Starting to populate the database but not use it in the view as long as we don't have enough data to safely use it. We display a 404 if we don't find the data in it when we would deploy the view.
* Starting to populate the database and rely on the old queries on `cache` and `ci_build_index` when the first query doesn't succeed (the best option IMO).
* To fill the database by querying the `cache` and `ci_build_index` if it exists to fill it with the data we already have. This one is the riskier.

**Comment by novemberkilo** [comment]
We have populated the new `ci_build_summary` table at the point where `Index.record` is called.
