### ISSUE TITLE
Line numbers in the thousands slightly exceed their column

### ISSUE THREAD

**Issue by MisterDA** [ocurrent/ocaml-ci#548]
Line numbers in the thousands slightly exceed their column.

![2022-10-06-17:32:20](https://user-images.githubusercontent.com/1773581/194355770-4a5ae2e1-09f8-4d61-b147-52908dd52a83.png)

**Comment by MisterDA** [comment]
![2022-10-07-15:40:39](https://user-images.githubusercontent.com/1773581/194567491-59d1129d-5001-4c43-b64b-19504edd6898.png)

also the anchor is slightly off

**Comment by novemberkilo** [comment]
@MisterDA I've deployed a fix. Can you please verify that things are improved ... and close as appropriate? Thanks.

**Comment by MisterDA** [comment]
It's great, but the anchor is slightly off still.

**Comment by novemberkilo** [comment]
> the anchor is slightly off still.

I'm not sure what this means @MisterDA - are you perhaps talking about the placement of the copy-link button?

**Comment by MisterDA** [comment]
Sorry, yes! It's not aligned with the line it's referring to.

**Comment by MisterDA** [comment]
The issue has disappeared ;) thank you Navin!
