### ISSUE TITLE
Ability to cancel a step

### ISSUE THREAD

**Issue by novemberkilo** [ocurrent/ocaml-ci#554]
A user can cancel an entire build but not an individual step. We should add a Cancel button for steps that can be cancelled (i.e. are not in states "passed" or "failed?").

**Comment by kit-ty-kate** [comment]
what are steps that can be cancelled?

**Comment by novemberkilo** [comment]
We've been using step to mean a job (a build is thus a collection of steps). A job can be canceled if it has not yet started, or is running.

**Comment by kit-ty-kate** [comment]
> A job can be canceled if it has not yet started, or is running.

I'm not sure to understand this ticket then

**Comment by benmandrew** [comment]
I think @novemberkilo means that a job _should_ be able to be cancelled, but it is not yet the case?

**Comment by novemberkilo** [comment]
A user can't cancel an individual job. This ticket addresses that.
