### ISSUE TITLE
link leads to internal server error

### ISSUE THREAD

**Issue by hannesm** [ocurrent/ocaml-ci#567]
from https://github.com/mirage/ocaml-conduit/pull/416 I can click on the CI check link https://github.com/mirage/ocaml-conduit/pull/416/checks?check_run_id=9069048253 which displays the "analysis phase failed" (for OCaml-CI), and when I click on the link titled "View more details on ocaml-ci " (at https://ci.ocamllabs.io/github/mirage/ocaml-conduit/commit/79c222f382df1c55f0680c80f069d74dc42ccd88/-/refs/pull/416/head), I receive an internal server error.

**Comment by maiste** [comment]
Thanks for reporting!
Until we fix this, you should be able to access the result of the build here: https://ci.ocamllabs.io/github/mirage/ocaml-conduit/commit/638c1730fc5360aa41a52e3a6d4e72ff43837d8c

**Comment by maiste** [comment]
https://github.com/ocurrent/ocaml-ci/pull/583 has addressed this. Feel free to reopen it if the bug appears again.
