### ISSUE TITLE
Backups of db for GitLab and GitHub services 

### ISSUE THREAD

**Issue by novemberkilo** [ocurrent/ocaml-ci#581]
We are introducing history of builds (at the branch/ref level) to ocaml-ci. To support this reliably we will need process and tools to backup and restore the databases associated with ocaml-ci -- namely the sqlite databases associated to the GitLab and GitHub services.

A first step to accomplishing this could be a sketch of the properties that our backup/restore process (and tools) would have. We should be clear on where we will use automation (e.g. on deploys, we backup the database before doing anything else), and, how we will restore from backup manually.

// @maiste @mtelvers

**Comment by maiste** [comment]
From a discussion with @tmcgilchrist, we should run a script regularly to back up the database instead of doing it when we deploy a new migration. IMHO, the backup process should be automatic, whereas the restoring part should be manual. Indeed, I'd like to think that we won't have to do it regularly: otherwise, it means we have failed in some other areas of development.

**Comment by maiste** [comment]
## Proposal

This is a proposition about how we can backup our system. We know that the `sqlite.db` is stored in the docker volume `ocaml-ci_data`. An easy backup system we can use is to rely on docker volumes. We create a new volume, `ocaml-ci_backup`. Then we run a docker with this kind of command:
 ```sh
 docker run --rm --name samwise \
                      -v "ocaml_ci-data:/data" \
                      -v "ocaml_ci-backup:/backup" \
                      busybox:latest -c "tar cvzf /backup/sqlite.db.tar.gz /data/sqlite.db"
```

The script should be a bit more complicated to ensure we don't erase the old backup before we have imported the new one, but coupled with a `cron` job, we should be able to have regular backups of our system. To __restore__ the data, we can do the opposite operation and extract the tar as the old database. 

:warning: A vital point to notice is that we need to __stop__ the service  `ocaml-ci_ci` before backing the database. We can expect to have paused in the CI system, which is not an issue if it takes less than _15 minutes_ once a week.

## Schema

```ascii
┌──────────────┐
│              │
│ ocaml-ci_ci  │
│              │
└────┬─────────┘
     │
     │
┌────▼──────────┐
│ ocaml-ci_data ◄────────────────┐
└───────────────┘                │
                           ┌─────┴──────┐
                           │  samwise   │
                           └──────┬─────┘
                                  │
                                  │
 ┌─────────────────┐              │
 │ocaml-ci_backup  ◄──────────────┘
 └─────────────────┘
```

<hr />


@mtelvers do you think it can be a good solution, or is there anything better we can do?

**Comment by novemberkilo** [comment]
Maybe example 2 here https://www.sqlite.org/backup.html will help us backup without needing to stop the service -- be nice not to have downtime (which requires its own tool 😄)

**Comment by mtelvers** [comment]
The `sqlite3` command line tool has a `.backup` command which takes a copy of an open database using appropriate locking.  The tool is available as a Docker container.  Therefore we can take a backup without stopping the `ocaml-ci`, something like this:

```
docker run --rm -it -v "ocaml-ci_data:/var/lib/ocurrent" -v "ocaml-ci_backup:/backup" --user 0:0 keinos/sqlite3 sqlite3 /var/lib/ocurrent/var/db/sqlite.db ".timeout 30000" ".backup /backup/sqlite.db"
```

**Comment by maiste** [comment]
@novemberkilo and @mtelvers can we consider this issue as done and close it?

**Comment by mtelvers** [comment]
Yes, I have created [PR#206](https://github.com/tarides/infrastructure/pull/206) for the backup script to run on a daily basis.
