### ISSUE TITLE
Repos page v2 -- Adding the graph of the last n builds and other metrics

### ISSUE THREAD

**Issue by novemberkilo** [ocurrent/ocaml-ci#588]

**Comment by novemberkilo** [comment]
I've spiked making the build history chart using [chart.js](https://www.chartjs.org/docs/latest/) on this codepen https://codepen.io/novemberkilo/pen/XWYgKOj

To drive the charts we will need, for each build in the previous 15(?) builds for the default branch of each repo:
- build status (passed | failed | unknown)
- build run time (in seconds)
- possibly a url to the build itself (so that clicking on the bar results in being directed to the build)

**Comment by benmandrew** [comment]
Solved by https://github.com/ocurrent/ocaml-ci/pull/668.

**Comment by novemberkilo** [comment]
Using this issue to track the work on repos page until it is properly in production.

**Comment by novemberkilo** [comment]
@benmandrew the build frequency numbers seemed a bit off to me - capturing here for further investigation/checking.

![Screenshot 2022-12-15 at 9 21 59 am](https://user-images.githubusercontent.com/181086/207814668-d3f0203c-3502-411c-9901-e62a9cbb12cc.png)
