### ISSUE TITLE
User not showing up in the list of organizations depite being whitelisted

### ISSUE THREAD

**Issue by mefyl** [ocurrent/ocaml-ci#601]
Despite [being added to the whitelist](https://github.com/ocurrent/ocaml-ci/commit/ce4397eec43d033e7f75c5af20a704f48bc80d5c), I cannot find myself in the [registered Github organization](https://ci.ocamllabs.io/github). At the very beginning I (mefyl) was listed there, but clicking the page [yielded a 500](https://ci.ocamllabs.io/github/mefyl). I supposed this could be some propagation issue and decided to give it some time, but I now disappeared from the list altogether. Did I miss something?

**Comment by maiste** [comment]
Hi!
Thanks for the report. To fully understand what could happen, do you have any repository where you have installed the [ocaml-ci GitHub App](https://github.com/apps/ocaml-ci)?

**Comment by mefyl** [comment]
Just did so, I suppose it will take some time to propagate.

**Comment by maiste** [comment]
It is available again: https://ci.ocamllabs.io/github/mefyl

There was a mistake on our side where the list wasn't up-to-date, and it's fixed now. 
Sorry for the inconvenience, and thanks for having raised the issue :+1:

**Comment by mefyl** [comment]
Awesome, thank you for the quick support!
