### ISSUE TITLE
Building on `opensuse-15.3-4.14_opam-2.1` fails with `conf-npm`

### ISSUE THREAD

**Issue by mefyl** [ocurrent/ocaml-ci#602]
It looks like installing node via `conf-npm` is [not supported](https://ci.ocamllabs.io/github/mefyl/timmy/commit/420203/variant/opensuse-15.3-4.14_opam-2.1) on the opensuse image. I suppose this architecture could be disabled when `conf-npm` is part of the dependencies ?

**Comment by kit-ty-kate** [comment]
This is an opam-repository issue where the package on opensuse should be `npm-default` instead of `npm` it looks like.
I don't seem to have the rights to move the issue to opam-repository but in any case a PR would be welcome.

**Comment by mefyl** [comment]
Done, thanks for the explanation 👍
