### ISSUE TITLE
UI instability on page load

### ISSUE THREAD

**Issue by benmandrew** [ocurrent/ocaml-ci#626]
It seems there is some CSS changed directly after a page loads in all pages in the new UI. This is seen primarily in the font changing from a standard to a bold font, but we also see in the build page that the table header is removed. Both of these are visually seen by the user on every page load, even on a refresh of the same page.

This is perhaps related to the tailwind CSS generation introduced in #605?

**Comment by novemberkilo** [comment]
I wonder if this is intermittent FOUC https://en.wikipedia.org/wiki/Flash_of_unstyled_content

**Comment by maiste** [comment]
Some issues can be related to the `10s` reload rate. Sometimes, we update the page CSS with some Javascript. If the CSS code is not the same, it can __break__ the page's design. It's another option to consider here.
