### ISSUE TITLE
Fails because of "tailwindcss"

### ISSUE THREAD

**Issue by moyodiallo** [ocurrent/ocaml-ci#628]
This package is not found in `opam repository`, why are we adding it in `dune-project` as a dependency.
https://github.com/ocurrent/ocaml-ci/blob/2408726883bd5f736d829b1f50b0dbdfa76035bc/dune-project#L135

The compiling the project after cloning and installing its dependencies.
```
12 |     (run tailwindcss -m -c %{config} -i %{input} -o %{target})))))
              ^^^^^^^^^^^
Error: Program tailwindcss not found in the tree or in PATH
 (context: default)
```

**Comment by novemberkilo** [comment]
@moyodiallo there is a pin for `tailwindcss` here: https://github.com/ocurrent/ocaml-ci/blob/master/ocaml-ci-web.opam.template#L6 -- did that not get installed for you?

**Comment by moyodiallo** [comment]
Thanks, I missed that, by changing my `opam switch` and installing the deps with old branch.

**Comment by novemberkilo** [comment]
No worries :) - ok to close?
