### ISSUE TITLE
macOS runner has some trouble

### ISSUE THREAD

**Issue by hannesm** [ocurrent/ocaml-ci#635]
From a project (mirage/ocaml-dns) that has ocaml-ci setup, the macOS runner is having some issues. I checked the file "packages/dkml-runtime-distribution/dkml-runtime-distribution.1.0.2~prerel7/opam", which as first line contains `opam-version: "2.0"` -- so I do not understand what the issue is.

```
2022-11-24 17:18.56 ---> using "837878c522e0e5fd5997751038969a0e289cb49273df4c42feef3ceec1e20f42" from cache
--


<pre>2022-11-24 17:20.03: Error: Could not update repository "default": In /private/var/folders/6j/3jv3qzh115v033d0sd89x3k40000z8/T/opam-65325-773a4c/default/packages/dkml-runtime-distribution/dkml-runtime-distribution.1.0.2~prerel7/opam:</pre>
```

See the full log at https://ci.ocamllabs.io/github/mirage/ocaml-dns/commit/422b032bf8a74afe8c311407890a04ea87e55fac/variant/macos-homebrew-4.14.0_arm64_opam-2.1

**Comment by hannesm** [comment]
And somehow, copy & pasting the output doesn't work nicely in Firefox. I can paste it into vi, but not into Firefox (see the crippled output above).

**Comment by tmcgilchrist** [comment]
@hannesm thank you for the bug reports. 

We are in the process of introducing macOS x86 and arm64 support for ocaml-ci. Apologies for the bumps along the way. 
I'm looking at this problem, initial thoughts are the git cache got corrupted but I need to do more investigation.

The issue with copying output is being looked at and should be fixed real soon.

**Comment by hannesm** [comment]
Thanks for your work on this.

> We are in the process of introducing macOS x86 and arm64 support for ocaml-ci. Apologies for the bumps along the way.

Hmm, would it be possible to either run them on a staging CI, so that not every repository using ocaml-ci sees these failures? Or have these checks marked as "ok-to-fail" until their state is more stable?

Thanks a lot!

**Comment by tmcgilchrist** [comment]
@hannesm failing macOS builds should no longer fail the overall build. We will still run the macOS builds and report the errors in the summary eg https://github.com/ocurrent/ocurrent/runs/9914823111 fails on macOS but the overall build is marked as passed. The build logs for the failing builds are available on `ci.ocamllabs.io` linked from the GitHub UI. 

As we fix the bugs with macOS and gain more confidence it is stable, we plan to change the behaviour so it does fail the build. In future we also want to add new builds for things like Windows or FreeBSD under a similar process. 

I hope that addresses things, please get in touch if you encounter other issues.

**Comment by tmcgilchrist** [comment]
The macOS support has been more stable since switching the macOS workers over to ZFS from rsync. 
Please get in touch if you encounter other issues.
