### ISSUE TITLE
Github profile pictures rate limit

### ISSUE THREAD

**Issue by benmandrew** [ocurrent/ocaml-ci#638]
On the organisations page, to get Github profile pictures we simply use the Github URL (`github.com/[username].png`). If you refresh the page a few times the images will fail to load with a 429 rate-limit error. (Best to try on https://ci.ocamllabs.io rather than locally because of the number of orgs.)

In the long term we could think about some way of caching the initial results with a timeout, but for now I will implement a fallback Github image like what we have by default for Gitlab.

**Comment by novemberkilo** [comment]
#639 should address this.
