### ISSUE TITLE
Show only the first line of the commit message as title

### ISSUE THREAD

**Issue by MisterDA** [ocurrent/ocaml-ci#655]
In case the commit message spans multiple lines, it'll be displayed fully as a title. We probably only want the first line.

![2022-12-05-10:55:37](https://user-images.githubusercontent.com/1773581/205608201-72ed5eb0-b876-4f27-bd99-97bf06677256.png)

**Comment by novemberkilo** [comment]
This has been addressed in #659 // @maiste

**Comment by maiste** [comment]
Merged! Feel free to reopen if it happens again.
