### ISSUE TITLE
Documentation: page by theme documentation

### ISSUE THREAD

**Issue by maiste** [ocurrent/ocaml-ci#690]
This issue provides a way to track improvement in User Documentation. It's a following for #595. `ocaml-ci` needs to have pages to explain each page and what is the information on it:
- [x] Organisation
- [x] Repo
- [x] Build
- [x] Step
- [x] History

**Comment by novemberkilo** [comment]
Covered in #699

**Comment by maiste** [comment]
Closing as it's done.
