### ISSUE TITLE
Add linting on package lower bounds

### ISSUE THREAD

**Issue by tmcgilchrist** [ocurrent/ocaml-ci#715]
Currently the solver gets the most recent version of a package that is available from opam repo and doesn't check whether the lower bounds are sensible. The first time lower bounds are checked is when a package is submitted to opam-repo-ci.

It should be possible to validate either:
 1. The lowest bounds on all possible packages for the oldest supported OCaml version
 2. For all supported OCaml versions, check the lower bounds.

Initially supporting 1 would be less CPU load and sufficient to validate the idea. Then look at extending it to all OCaml versions on Linux (x86/ARM64), since we have lots of capacity there compared to macOS or other architectures. See [opam-repo-ci](https://github.com/ocurrent/opam-repo-ci ) for how it implements lower bounds checking.

**Comment by benmandrew** [comment]
(1) is implemented in #727. (2) can be easily added.
