### ISSUE TITLE
4.14.1 not on the ocaml-ci yet

### ISSUE THREAD

**Issue by avsm** [ocurrent/ocaml-ci#717]
This breaks RWO attempting to update to 4.14.1 as only 4.14.0 is available.

https://ci.ocamllabs.io/github/realworldocaml/book/commit/3d8469813cf0518d8d3cefc682d629c8040f5adb/variant/debian-11-4.14_opam-2.1

**Comment by dra27** [comment]
It's fixed - or at least, the 4.14.1 part of it is!

**Comment by avsm** [comment]
Thanks! Indeed, it's failing "healthily" now ;-)
