### ISSUE TITLE
Steps to reproduce code block is incorrect

### ISSUE THREAD

**Issue by tmcgilchrist** [ocurrent/ocaml-ci#728]
## Context

Steps to reproduce code block is incorrect. 

## Step(s) to reproduce

Use either the `Copy Code` button or manually select the full section of `Steps to Reproduce`. 
The PR section of the git clone is incorrect `git fetch origin "refs/pull//head" ` missing the PR number.
Also the `Copy Code` button doesn't give any visual feedback that anything has been copied. 

The reproductions steps are correct in the log file. I expect the code extracting it from the logs is to blame.

## Expected behaviour

I should be able to use either the button or select a section to copy the reproduction steps.
## Technical details

Using macOS 12.6.2  / Safari 16.2

## Additional context

The bug is present on this build. https://ci.ocamllabs.io/github/realworldocaml/book/commit/fc64a884f84226047d0031984b7058ea75353ffc/variant/debian-11-4.14_opam-2.1

**Comment by maiste** [comment]
Fixed in #731
