### ISSUE TITLE
Timestamp being confusing.

### ISSUE THREAD

**Issue by maiste** [ocurrent/ocaml-ci#739]
From a discussion with @emillon and @samoht, two issues with timestamps were raised:
1.  The naming "Speed" is confusing:  users can't know what it really is.
> As an example, "higher speed" means a decrease in this number
2. The `Total build time` metric should be displayed only if the user requests. Indeed, maintainers need information about the efficiency of their builds, not about how much it "cost" to run their programs.
> as a maintainer, the metric I'm after is how much time I have to wait before having useful info. so it would be the max of all builds. (or P95 of this). the sum of build times is a useful metric for €/energy/CO2 but not the first thing I'm after as a maintainer

> in terms of UX (for someone that wants to test the system), this is quite confusing and not very appealing. In CI, the first thing people care about is how long they have to wait to get their feedback. That should be main metrics we push forward.

**Comment by novemberkilo** [comment]
I'd like to help us arrive at consensus on what we should do to improve upon the current situation. From the discussion I think that the main issue is with the organisation page and the terms **Speed over time** and **Speed** that appear there (and only there). 

![Screenshot 2023-03-08 at 11 57 07 am](https://user-images.githubusercontent.com/181086/223593862-b22f7741-db68-4e47-bebc-a1a1a32a1ba4.png)


**Proposal**
1. Remove the title "Speed over time" 
2. Replace "Speed" with "Mean run time"
3. Include tooltips for "Mean run time" "Reliability" and "Build frequency" 


For reference, this is what Buildkite do:

![Screenshot 2023-03-08 at 11 51 11 am](https://user-images.githubusercontent.com/181086/223591542-03f1c194-407e-43f4-b9ee-12ad331572b1.png)
---

There are also timestamps and durations shown on the build page -- we use the language "Total run time" and "Ran for" to indicate two separate metrics. We emphasise "Ran for" and this represents the wall-clock time that a build takes. We also report in small font on Total run time and this indicates the cumulative time across all resources used by the build.

![Screenshot 2023-03-08 at 11 55 26 am](https://user-images.githubusercontent.com/181086/223592032-50261c80-6eef-4b73-8e62-5c2086c40dc3.png)

As far as I can tell this is all ok and there are no objections or suggestions to change this. It would be good to confirm this.

---

@samoht @emillon @benmandrew @maiste @tmcgilchrist please would you indicate your thoughts - specifically on the proposal for next steps?

**Comment by tmcgilchrist** [comment]
@novemberkilo that sounds good. 

The speed values got cooked by macos builds failing and the workers being overloaded. Since then we’ve removed the macos build times contribution to Speed since they are Experimental and also working on speeding up the macos builds with various fixes. When the builds are considered stable we need to add them back into the Mean Build time.

**Comment by maiste** [comment]
@novemberkilo I agree with the proposal.

From the discussion we could have had offline, I would suggest removing the `Total build run time` from the page. Indeed, this is what `GitHub` do, and it only shows the `Total run_time` for the paying part as it is the reference for the money part. As it isn't monetised here, I suggest removing it to keep the `parallel` time as our reference for users.

**Comment by benmandrew** [comment]
Seconding @maiste, I agree with the proposal and think that for users the total run time is at best unnecessary and at worst confusing.

**Comment by samoht** [comment]
Might I also suggest to separate the mean time for waiting time vs. build time?

ie. on https://ci.ocamllabs.io/github/samoht/depyt/commit/58dc17c37159a266dc677dfff3176c9ab7218504 it says `Ran for 40m37s` but all the runs took a few seconds - however, the analysis step was stuck `40m19s` in the queue. I'd suggest surfacing this in the UX.
