### ISSUE TITLE
Running experimental steps should not prevent the CI from succeeding

### ISSUE THREAD

**Issue by benmandrew** [ocurrent/ocaml-ci#740]
Experimental builds (currently `macos-*` and `lint-lower-bounds`) should be ignored when deciding whether the CI has succeeded or not in the CI UI. Currently this works only when experimental builds have failed, but should also happen while they are running.

It is also unclear whether this is working in the GitHub actions UI (for both failed and running experimental builds):

<img width="719" alt="Screenshot 2023-01-25 at 11 59 18" src="https://user-images.githubusercontent.com/13054139/214546395-48deef0e-873a-4eaf-84a9-f810b8541b9e.png">

**Comment by maiste** [comment]
Fixed in #741. Feel free to reopen if it happens again.
