### ISSUE TITLE
Rebuild on `lint-fmt` yields a 404 NotFound

### ISSUE THREAD

**Issue by art-w** [ocurrent/ocaml-ci#777]
## Step(s) to reproduce

- Go to a failed `lint-fmt` page on the CI, for example https://ci.ocamllabs.io/github/mirage/irmin/commit/9526a48bc614dba93bef1837b40d0cf297abaf25/variant/%28lint-fmt%29
- Click the "Rebuild" button on the top right
- Get a 404 NotFound page

## Expected behaviour

The job should rebuild and display the new logs (or display a different error message than NotFound if this action is invalid)

**Comment by maiste** [comment]
My suspicion is that there was an error when I refactored the code of the router and it point to the wrong page now.

**Comment by novemberkilo** [comment]
This is the case for any of the lint-* steps. Rebuild does however work fine for other steps.
