### ISSUE TITLE
Logs not displaying on Safari

### ISSUE THREAD

**Issue by benmandrew** [ocurrent/ocaml-ci#803]
## Context

On Safari the logs do not display, and in the console there is the warning (for example):
```
[blocked] The page at
https://ocaml.ci.dev/github/ocurrent/obuilder/commit/d60e6b427a8d09a54d231a60ab233584346cfc4d/variant/debian-11-4.14_x86_32_opam-2.1
was not allowed to run insecure content from
ws://ocaml.ci.dev/ws/github/ocurrent/obuilder/commit/d60e6b427a8d09a54d231a60ab233584346cfc4d/variant/debian-11-4.14_x86_32_opam-2.1.
```

This occurs for all logs pages including analyses.

## Additional context

Apparently this seems to be a relatively old quirk of Safari (https://stackoverflow.com/questions/32883306/safari-9-disallowed-running-of-insecure-content). I don't know enough about secure content serving to know what's wrong here.

## Screenshots

<img width="654" alt="Screenshot 2023-04-04 at 10 38 39" src="https://user-images.githubusercontent.com/13054139/229740524-3cb04b48-8f21-4a6a-9f0c-4e230279a4ba.png">

**Comment by novemberkilo** [comment]
This is now fixed. The issue was that it was deployed so that the browser would request a websockets connection without SSL. Changing the scheme from `ws://` to `wss://` appears to have fixed the problem.
