### ISSUE TITLE
OCamlformat version makes the analysis fail

### ISSUE THREAD

**Issue by Julow** [ocurrent/ocaml-ci#834]
## Context

I opened PRs with the next unreleased version of OCamlformat applied. The `version` field in `.ocamlformat` contains an invalid value.

## Step(s) to reproduce

```
echo "version = 0.99.0" > .ocamlformat
```

## Expected behaviour

The version of OCamlformat seems to be resolved for every compilers and every compilers fail to resolve due to that.

I would expect:

- OCamlformat is only resolved for the "fmt" job. 
- If the "fmt" job fails to be resolved, other jobs are not interrupted and the CI run with an always failing "fmt" job.

## Additional context

For example, in Odoc on this PR: https://github.com/ocaml/odoc/pull/979
CI result: https://ocaml.ci.dev/github/ocaml/odoc/commit/f42fd067a329da36ef64f1f2cdac75967da60885/variant/%28analysis%29

**Comment by moyodiallo** [comment]
The fix for this issue is deployed, would you like to validate the result observed here https://ocaml.ci.dev/github/moyodiallo/odoc/commit/28c31b974605701babfd0c645d0b8de5c68d6591 (same link as above).
 @Julow

**Comment by Julow** [comment]
That fixes my issue, thanks :)

Though the error message isn't nice:
> Error: Program ocamlformat not found in the tree or in PATH

The job might as well fail immediately with a clearer message.

**Comment by moyodiallo** [comment]
> The job might as well fail immediately with a clearer message.

You're right, verifying if the ocamlformat version is available from the analysis result.

**Comment by benmandrew** [comment]
Is this fixed by #865 @moyodiallo?

**Comment by moyodiallo** [comment]
After the merge of #877, we can close this.

**Comment by gpetiot** [comment]
We still observe this on ocamlformat's repository: https://github.com/ocaml-ppx/ocamlformat/runs/17517278251

(we don't have a set version in the .ocamlformat file because we use the version of the same commit to format ocamlformat's codebase)

**Comment by moyodiallo** [comment]
Keep in mind those 2 issues are different. what you're describing is ocamlformat without version. I think It could be preferable to open another issue.

**Comment by benmandrew** [comment]
@moyodiallo you're right, I've opened another issue.
