### ISSUE TITLE
big duniverses exceed layer count in depext calculation

### ISSUE THREAD

**Issue by avsm** [ocurrent/ocaml-ci#85]
The `COPY` and `opam pin` strategy for depext calculation leads to a large number of layers in the resulting Dockerfile.  There is a limit (127) of these in the engine, which leads to build failures.

I think we need a more efficient (but still cache-friendly) way to do the opam pin / depext dance that doesn't add a lot of layers.  Some options:

- copy all the opam files into a _single_ directory and then pin them all there. This would let it work in a single COPY command.
- we could create a new layer for all the opam pins, and subsequently roll that back.

I suspect the first option is best...

**Comment by talex5** [comment]
Another way would be to tar them up and then ADD the tar file (Docker might even untar it automatically; can't remember).

**Comment by avsm** [comment]
indeed! This is supported with `ADD`: https://docs.docker.com/engine/reference/builder/#add

> If <src> is a local tar archive in a recognized compression format (identity, gzip, bzip2 or xz) then it is unpacked as a directory. Resources from remote URLs are not decompressed. When a directory is copied or unpacked, it has the same behavior as tar -x, the result is the union of:

**Comment by talex5** [comment]
Was fixed in #142.
