### ISSUE TITLE
`lint-doc` uses lower-bounds for installing dependencies

### ISSUE THREAD

**Issue by edwintorok** [ocurrent/ocaml-ci#872]
## Context

Although using lower-bounds for installing packages is a good way to find bugs there are other CI steps that do that already (and a lower-bound failure may be due to a dependency of a package and not a bug in the package being tested).
To maximize the usefulness of the `lint-doc` step it should focus on linting the documentation and the best chance of doing that successfully is by installing the latest version of all dependencies as `opam` normally would.

## Step(s) to reproduce

https://ocaml.ci.dev/github/edwintorok/lintcstubs/commit/8db4abc2ae1f8c579940a6a98940a41419a7aca0/variant/%28lint-doc%29

## Expected behaviour

`lint-doc` starts checking documentation and doesn't fail on installing dependencies.

## Technical details

There are other CI steps that show that the package itself does build when not using lower bounds (and the lower bound bug is being fixed in an opam PR currently):
https://ocaml.ci.dev/github/edwintorok/lintcstubs/commit/8db4abc2ae1f8c579940a6a98940a41419a7aca0

**Comment by benmandrew** [comment]
Thanks for reporting, I missed this issue but ran into the same problem myself independently! Fixed by #878.
