### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by hannesm** [ocurrent/ocaml-ci#875]
Dear Madam or Sir,

thank you very much for your kind service. I noticed that copy and pasting the log output introduces for each line another empty line, which is annoying.

Furthermore, loading a biggish log (such as https://ocaml.ci.dev/github/mirage/mirage-crypto/commit/d496d32fcfed713c2eb170f1c1109d032435578a/variant/macos-homebrew-4.14.1_arm64_opam-2.1) and scrolling there / searching for text requires a huge amount of CPU and memory (likely related to CSS and JS)... -- could there be a "raw console output" mode where I don't get the fancy line numbers and colors and interactions, but a fast and low resource usage output?

Thanks for reading,

Hannes

**Comment by avsm** [comment]
On a similar note, ocaml-ci was designed to support capnp-based queries. It would also be nice if the raw logs were available via a CLI call as well as the web.  Something like

`$ ocaml-ci log <jobid>`

which would query the CI and just dump out the results.

**Comment by tmcgilchrist** [comment]
@avsm that functionality is still available. However it requires a cap file and we haven't worked out a good process for making those generally available as part of the ocaml-ci cli. 

@hannesm we are working on an option for providing raw console output in the web UI.

**Comment by benmandrew** [comment]
@hannesm thank you for the feedback. I am not seeing the extra newlines on both Safari and Chrome on Mac, what browser and platform are you using?

**Comment by hannesm** [comment]
My browser is Firefox, platform is FreeBSD.

**Comment by novemberkilo** [comment]
Reopening until the raw logs output is also available.
