### ISSUE TITLE
`lint-fmt` failing with file permission error

### ISSUE THREAD

**Issue by shonfeder** [ocurrent/ocaml-ci#940]
## Context

On https://ocaml.ci.dev/github/ocaml-multicore/picos/commit/9392f253fa5741352e552072335958d210334d0b/variant/%28lint-fmt%29

We are failing with

```
rm: cannot remove '/home/opam/.opam/4.08/.opam-switch/sources/astring.0.8.5/test/total.ml': Permission denied
rm: cannot remove '/home/opam/.opam/4.08/.opam-switch/sources/astring.0.8.5/test/testing.mli': Permission denied
rm: cannot remove '/home/opam/.opam/4.08/.opam-switch/sources/astring.0.8.5/test/testing.ml': Permission denied
```

## Step(s) to reproduce

Reruning the job is reproducing

## Technical details

I've run the steps on the base docker container, and it's working as expected. So it doesn't seem to be an issue with the base image.

**Comment by mtelvers** [comment]
I wonder if it is worker specific?  I've moved the job to another worker.  The queue is heavily backlogged so it'll be tomorrow before we see a result.

**Comment by shonfeder** [comment]
It is not worker specific. Happening now on x86-bm-c9.sw.ocaml.org :/ seems the file perms have been borked some how?

https://ocaml.ci.dev/github/ocurrent/ocaml-ci/commit/dd5494c1332e687b8ae0cf44e756ccaa26b87b47/variant/%28lint-fmt%29

**Comment by shonfeder** [comment]
This is fixed by https://github.com/ocurrent/ocaml-ci/commit/48ba2f5d40304286582710be440dab697e4a0b04

The cause was an error I introduced in #937 by mixing up the order of the docker actions. Sorry for the trouble and noise there.
