### ISSUE TITLE
Promote FreeBSD and MacOS to non-exprimental 

### ISSUE THREAD

**Issue by shonfeder** [ocurrent/ocaml-ci#944]
MacOS and FreeBSD are currently tagged as "experimental platforms":

https://github.com/ocurrent/ocaml-ci/blob/bd28414e04b4d743f290a0f6e3ff27ad8797cef4/lib/build_info.ml#L10-L37

Which means that even if those CI checks have failed or are not finished, the overall status of a job can show as green. This recently led to a problem, reported by @polytypic, where the development CI was showing all green, masking non-completing FreeBSD jobs that were actually signs of a problem. 

MacOS was added in cffaa14c320cc2803722f36bc1bcb9d208b86264, in Oct of 2022 and marked as experimental in Dec with b8f1733 .

FreeBSD was added more recently, just under a year ago, in c2df7fea51f0f166c06c19d2ff0f4fcb73a7ed0b.

However, we think it may be time to promote these variants to non-experimental targets.

Thoughts?

**Comment by polytypic** [comment]
Yes.  If some platform on OCaml-CI is too unstable for some reason for some project I'm developing, I might, for example, exclude that platform (at the package level) or skip tests via other means on OCaml-CI for that platform.

**Comment by mtelvers** [comment]
I would like to see both FreeBSD and macOS promoted out of `experimental`.

**Comment by tmcgilchrist** [comment]
I agree they are both stable and have sufficient capacity to be promoted
out of experimental.
