### ISSUE TITLE
HTTP 500 error on CI run

### ISSUE THREAD

**Issue by edwintorok** [ocurrent/ocaml-ci#946]
## Context

I get an immediate HTTP 500 failure on ocaml-ci runs

## Step(s) to reproduce

https://ocaml.ci.dev/github/mirage/bechamel/commit/5217bb98a504d82c2474e4cfe2fa9c76ac070ce2/variant/%28analysis%29
https://ocaml.ci.dev/github/mirage/bechamel/commit/1c04621871725d7c6ee5c7a1bff17e8af5456985/variant/debian-12-4.14_s390x_opam-2.1

https://ocaml.ci.dev/github/mirage/bechamel/commit/1c04621871725d7c6ee5c7a1bff17e8af5456985/variant/debian-11-5.2_opam-2.1

## Expected behaviour

I expected to see some logs from the build, or for a new CI run to start, but all logs seem to return 500 now from `mirage/bechamel`.
In particular https://ocaml.ci.dev/github/mirage/bechamel/commit/1c04621871725d7c6ee5c7a1bff17e8af5456985/variant/debian-11-5.2_opam-2.1 is reported as passed to github actions, and I was previously able to see its logs.

## Technical details

```
❌ (analysis) (failed: Command "docker" "run" "-i" "ocurrent/ocaml-ci:debian-12-ocaml-4.14"
"opam" "list" "-s" "--base" "--roots" "--all-versions" "ocaml-base-compiler"
"ocaml-variants" "ocaml-system" exited with status 99)
```

First observed during https://github.com/mirage/bechamel/runs/25998133914, which seems to have been mostly green, except for some in-progress jobs, which then turned into a 500 error.

## Additional context

Also it looks like some jobs were rebuilding the compiler itself.

**Comment by mtelvers** [comment]
The CI is now running again.  Your current logs are available https://github.com/mirage/bechamel/pull/52/checks?check_run_id=25998416656

**Comment by edwintorok** [comment]
thanks, we can close this issue now.
