### ISSUE TITLE
Test against beta versions of OCaml

### ISSUE THREAD

**Issue by CraigFe** [ocurrent/ocaml-ci#96]
Related to https://github.com/ocurrent/ocaml-ci/issues/95, we could test against beta / release-candidate versions of the OCaml compiler, and would likely want any failures to be non-fatal to CI. 

Support for the GitHub Checks API would allow us to report this information back to GitHub without failing the CI, but even just showing the result on the web API is a step in the right direction.

**Comment by avsm** [comment]
Support for beta compilers is now live since https://github.com/ocurrent/ocaml-ci/pull/195
