### ISSUE TITLE
ERROR while fetching sources

### ISSUE THREAD

**Issue by hannesm** [ocurrent/ocaml-ci#962]
Dear Madam or Sir,

I can see quite some issues since a few days that look like your worker cluster is unhappy. Rebuilding such jobs does not result in proper solutions. If you have some time, it would be great if you could have a look into the permission issue below.

```
#=== ERROR while fetching sources for randomconv.0.2.0 ========================#
OpamSolution.Fetch_fail("Cannot copy /home/opam/.opam/4.14/.opam-switch/sources/randomconv.0.2.0/randomconv-0.2.0.tbz to /home/opam/.opam/download-cache/sha512/37/376c36da6b67ed1d817ea13fbbc3490f356f0890f9e009a55d12946c6811611ea9bd31aec733dd961de7209effa23649505f61d1ed3fc18af225ca4ec9131c38 (/usr/bin/opam: \"open\" failed on /home/opam/.opam/download-cache/sha512/37/376c36da6b67ed1d817ea13fbbc3490f356f0890f9e009a55d12946c6811611ea9bd31aec733dd961de7209effa23649505f61d1ed3fc18af225ca4ec9131c38: Permission denied).")


#=== ERROR while fetching sources for ppx_bench.v0.16.0 =======================#
OpamSolution.Fetch_fail("Cannot copy /home/opam/.opam/4.14/.opam-switch/sources/ppx_bench.v0.16.0/ppx_bench-v0.16.0.tar.gz to /home/opam/.opam/download-cache/sha256/e3/e307fc25b4cb38125685fa01888255d00aaf6c1b82f52c4f02ebd48a4471761d (/usr/bin/opam: \"open\" failed on /home/opam/.opam/download-cache/sha256/e3/e307fc25b4cb38125685fa01888255d00aaf6c1b82f52c4f02ebd48a4471761d: Permission denied).")


#=== ERROR while fetching sources for core_kernel.v0.16.0 =====================#
OpamSolution.Fetch_fail("Cannot copy /home/opam/.opam/4.14/.opam-switch/sources/core_kernel.v0.16.0/core_kernel-v0.16.0.tar.gz to /home/opam/.opam/download-cache/sha256/e3/e37370bad978cfb71fdaf2b1a25ab1506b98ef0b91e0dbd189ffd9d853245ce2 (/usr/bin/opam: \"open\" failed on /home/opam/.opam/download-cache/sha256/e3/e37370bad978cfb71fdaf2b1a25ab1506b98ef0b91e0dbd189ffd9d853245ce2: Permission denied).")
```
from https://ocaml.ci.dev/github/mirleft/ocaml-tls/commit/9d6554335d8b1373a2463d7505fdb362fe13df8e/variant/fedora-40-4.14_opam-2.2

**Comment by hannesm** [comment]
FWIW, I can as well spot this issue on the opam repository CI.

**Comment by shonfeder** [comment]
Thank you for the report! We'll look into it.

**Comment by punchagan** [comment]
Thanks for the report, @hannesm.

I've tried investigating the issue locally using the Dockerfile, but haven't been able to reproduce it. We'll look into it, further.

**Comment by shonfeder** [comment]
Looking at https://ocaml.ci.dev/github/mirleft/ocaml-tls/commit/9d6554335d8b1373a2463d7505fdb362fe13df8e, I only see this failure occurring on 3

**Comment by mtelvers** [comment]
All of the failed jobs are on the machine `asteria`.  Investigating the cache on this machine showed that the permissions on a few of the cache files were `root:root` rather than `opam:opam`. These permissions have been updated.  Rebuilding the jobs now works.  There is nothing obvious in the log to indicate why these permissions were wrong.

**Comment by shonfeder** [comment]
Sounds like this has been resolved for the time being. If it recurs, we have have enough context here to help support a root cause investigation, and we can reopen.
