### ISSUE TITLE
Investigate marking `opam-dune-lint` check as non-experimental

### ISSUE THREAD

**Issue by punchagan** [ocurrent/ocaml-ci#969]
`opam-dune-lint` does some useful checks, for instance, ensuring projects have LICENSE files and license entries.  It looks like a bunch of projects fail the lower bounds check, though. 

Investigate what it would take to mark the check as non-experimental.

**Comment by punchagan** [comment]
The `license` check in `opam-dune-lint` is a warning and doesn't fail the check. :shrug:

**Comment by shonfeder** [comment]
Since this wouldn't even solve the problem we had in mind, maybe we can just close this investigation as solved?
