### ISSUE TITLE
CI anaysis is failing with an internal error

### ISSUE THREAD

**Issue by shonfeder** [ocurrent/ocaml-ci#984]
We are seeing in CI jobs:

```
 (analysis) (failed: Failed: Internal error)
```

I wonder if it is possible that https://github.com/ocurrent/ocaml-ci/pull/980 broke the CI, as this is the first commit where the master here when red. Tho it could be a coincidence.

**Comment by mtelvers** [comment]
No, it's #982 which broke it.  I have already reverted it on `live`.  The actual fix is to merge https://github.com/ocaml/opam-repository/pull/26909

**Comment by mtelvers** [comment]
Service is restored.
