### ISSUE TITLE
OCaml 5.1 is not being tested for some reason

### ISSUE THREAD

**Issue by talex5** [ocurrent/ocaml-ci#987]
## Context

capnp-rpc is not being tested on OCaml 5.1, even though the analysis step finds a solution.

See e.g. CI for https://github.com/mirage/capnp-rpc/tree/lwt.

Analysis says (not sure why there are two; 32-bit and 64-bit?):
```
2024-11-30 09:46.07 [INFO] debian-12-5.1_opam-2.3: found solution in 2.16 s
2024-11-30 09:46.08 [INFO] debian-12-5.1_opam-2.3: found solution in 2.89 s
```

But there are no 5.1 builds shown.

(found by opam-repo-ci when making a release)

## Technical details

This code looks wrong to me:

https://github.com/ocurrent/ocaml-ci/blob/cc9bac43c99dedc42a48b4dc1982157f87a98132/lib/pipeline.ml#L79-L82

**Comment by shonfeder** [comment]
5.1 is being tested now after #989. See https://github.com/ocurrent/ocaml-ci/runs/34042001228  

Thanks for the report!
